"use client";
import {useState} from "react";
import {Activity, BarChart3, Bell, Bot, Building2, ChevronDown, CircleDollarSign, Home, Inbox, MapPin, Menu, MessageCircle, Phone, Plus, Search, Settings, Sparkles, Target, Users} from "lucide-react";

const nav=[
 ["Workspace",[["Dashboard",Home],["Contacts",Users],["Companies",Building2],["Leads",Target],["Deals",CircleDollarSign],["Activities",Activity]]],
 ["Engagement",[["Campaigns",MessageCircle],["Inbox",Inbox],["Calls",Phone],["Automations",Sparkles]]],
 ["Growth",[["Business Finder",MapPin],["Analytics",BarChart3],["AI Assistant",Bot]]],
 ["System",[["Settings",Settings]]]
];
const deals=[{name:"Acme Retail",value:"₹2.4L",owner:"MG",stage:0},{name:"Bright Dental",value:"₹86K",owner:"AK",stage:0},{name:"Northstar Foods",value:"₹1.2L",owner:"RS",stage:1},{name:"Urban Studio",value:"₹64K",owner:"MG",stage:1},{name:"Green Leaf",value:"₹3.1L",owner:"PK",stage:2},{name:"Metro Labs",value:"₹1.8L",owner:"AK",stage:2},{name:"Nova Tech",value:"₹2.9L",owner:"RS",stage:3},{name:"Sunrise Hotel",value:"₹1.1L",owner:"MG",stage:4}];
const stages=["New lead","Contacted","Qualified","Proposal","Won"];
const campaigns=[['Weekend Sale','WhatsApp + Instagram','Scheduled','Aug 22, 10:00 AM'],['Bengaluru Re-engagement','WhatsApp','Running','1,284 recipients'],['New Product Launch','Email + Facebook','Completed','4,820 recipients']];
const activities=[['WhatsApp','Priya requested a callback','2 min ago'],['Deal','Green Leaf moved to Proposal','18 min ago'],['Lead','New lead from Business Finder','34 min ago'],['Campaign','Weekend Sale scheduled','1 hr ago']];
export default function Home(){
 const [active,setActive]=useState('Dashboard'); const [open,setOpen]=useState(false);
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="brandMark">P</div>Promote_Me</div>{nav.map(([section,items]:any)=><div key={section}><div className="navSection">{section}</div>{items.map(([label,Icon]:any)=><button key={label} className={`navItem ${active===label?'active':''}`} onClick={()=>setActive(label)}><Icon size={16}/>{label}</button>)}</div>)}</aside>
  <div className="main">
   <header className="topbar"><button className="iconBtn mobileOnly"><Menu size={18}/></button><div className="search"><Search size={16}/><input placeholder="Search contacts, companies, deals..."/><kbd className="hideMobile">⌘ K</kbd></div><div className="actions"><button className="iconBtn"><Bell size={17}/></button><button className="iconBtn"><Bot size={17}/></button><div className="avatar">MG</div></div></header>
   <main className="content">
    <div className="pageHead"><div><h1>Good evening, Mudigouda</h1><div className="muted small">Wednesday, August 19 · Here's what needs your attention.</div></div><button className="btn primary" onClick={()=>setOpen(!open)}><Plus size={16}/> New campaign</button></div>
    {open&&<div className="card" style={{marginBottom:16}}><b>Quick campaign</b><p className="muted small">Choose an audience, channel and schedule. Real provider connections can be added from Settings.</p><div className="quick"><button className="btn soft">WhatsApp campaign</button><button className="btn">Email campaign</button><button className="btn">Social post</button><button className="btn">AI draft</button></div></div>}
    <section className="grid4">{[['Total contacts','12,480','+8.2%'],['Open deals','₹18.6L','+12.4%'],['Active campaigns','8','+2 this week'],['Conversion rate','6.8%','+1.1%']].map(([l,v,t])=><div className="card kpi" key={l}><div><div className="label">{l}</div><div className="value">{v}</div></div><span className="trend">{t}</span></div>)}</section>
    <div className="grid3" style={{marginTop:16}}><section className="card" style={{gridColumn:'span 2'}}><div className="sectionTitle"><h2>Sales pipeline</h2><button className="btn">View pipeline <ChevronDown size={14}/></button></div><div className="pipeline">{stages.map((s,i)=><div className="stage" key={s}><div className="stageHead"><span>{s}</span><span>{deals.filter(d=>d.stage===i).length}</span></div>{deals.filter(d=>d.stage===i).map(d=><div className="deal" key={d.name}><b>{d.name}</b><div className="muted small">{d.value} · {d.owner}</div></div>)}</div>)}</div></section><section className="card"><div className="sectionTitle"><h2>Campaign performance</h2><button className="btn">30d</button></div><div className="chart">{[42,60,48,75,55,84,68,92,70,98].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}/>)}</div><div className="muted small">Messages delivered · 96.4%</div></section></div>
    <div className="grid3" style={{marginTop:16}}><section className="card" style={{gridColumn:'span 2'}}><div className="sectionTitle"><h2>Recent campaigns</h2><button className="btn">View all</button></div><div className="tableWrap"><table className="table"><thead><tr><th>Campaign</th><th>Channels</th><th>Status</th><th>Schedule / reach</th></tr></thead><tbody>{campaigns.map(c=><tr key={c[0]}><td><b>{c[0]}</b></td><td>{c[1]}</td><td><span className={`badge ${c[2]==='Running'?'blue':c[2]==='Completed'?'green':'orange'}`}>{c[2]}</span></td><td>{c[3]}</td></tr>)}</tbody></table></div></section><section className="card"><div className="sectionTitle"><h2>Needs attention</h2></div>{[['8','Overdue follow-ups'],['14','Leads waiting for contact'],['5','Callback requests'],['3','AI recommendations']].map(x=><div className="activity" key={x[1]}><div className="dot"/><div><b>{x[0]}</b> <span className="muted small">{x[1]}</span></div></div>)}</section></div>
    <div className="grid3" style={{marginTop:16}}><section className="card"><div className="sectionTitle"><h2>Activity timeline</h2><button className="btn">All</button></div>{activities.map(a=><div className="activity" key={a[1]}><div className="dot"/><div><b>{a[0]}</b> · {a[1]}<div className="muted small">{a[2]}</div></div></div>)}</section><section className="card"><div className="sectionTitle"><h2>AI Assistant</h2><Bot size={18}/></div><p className="muted">Ask Promote_Me to summarize customers, draft campaigns, find leads, or explain performance.</p><button className="btn soft">Open AI assistant</button></section><section className="card"><div className="sectionTitle"><h2>Business Finder</h2><MapPin size={18}/></div><p className="muted">Find public business information by category and location, then save qualified businesses to CRM.</p><button className="btn soft">Find businesses</button></section></div>
   </main>
  </div>
  <nav className="bottomNav"><a className="active"><Home size={18}/>Home</a><a><Users size={18}/>Leads</a><a><Inbox size={18}/>Inbox</a><a><Phone size={18}/>Calls</a><a><Menu size={18}/>More</a></nav>
 </div>
}
