"use client";
import {useState} from "react";
import {Activity,BarChart3,Bell,Bot,Building2,CalendarDays,ChevronRight,CircleDollarSign,Home,Inbox,MapPin,Menu,MessageCircle,Phone,Plus,Search,Settings,Sparkles,Target,Users,Mail,Globe,ShieldCheck} from "lucide-react";

const nav=[
 ["Workspace",[["Dashboard",Home],["Contacts",Users],["Companies",Building2],["Leads",Target],["Deals",CircleDollarSign],["Activities",Activity]]],
 ["Engagement",[["Campaigns",MessageCircle],["Inbox",Inbox],["Calls",Phone],["Automations",Sparkles]]],
 ["Growth",[["Business Finder",MapPin],["Analytics",BarChart3],["AI Assistant",Bot]]],
 ["System",[["Settings",Settings]]]
];
const contacts=[['Priya Sharma','ABC Retail','+91 98765 43210','Bengaluru','Hot'],['Rahul Kumar','Northstar Foods','+91 99887 11223','Mysuru','Warm'],['Anita Rao','Bright Dental','+91 98450 55667','Bengaluru','New'],['Vikram Singh','Urban Studio','+91 90000 12345','Hyderabad','Hot']];
const companies=[['ABC Retail','Retail','Bengaluru','12 contacts','₹4.2L'],['Northstar Foods','Food','Mysuru','8 contacts','₹2.1L'],['Bright Dental','Healthcare','Bengaluru','5 contacts','₹86K'],['Urban Studio','Design','Hyderabad','4 contacts','₹64K']];
const deals=[['Acme Retail','₹2.4L','New lead'],['Northstar Foods','₹1.2L','Contacted'],['Green Leaf','₹3.1L','Qualified'],['Nova Tech','₹2.9L','Proposal'],['Sunrise Hotel','₹1.1L','Won']];
const campaigns=[['Weekend Sale','WhatsApp + Instagram','Scheduled','Aug 22 · 10:00 AM'],['Bengaluru Re-engagement','WhatsApp','Running','1,284 recipients'],['New Product Launch','Email + Facebook','Completed','4,820 recipients']];
const activities=[['WhatsApp','Priya requested a callback','2 min ago'],['Deal','Green Leaf moved to Proposal','18 min ago'],['Lead','New lead from Business Finder','34 min ago'],['Campaign','Weekend Sale scheduled','1 hr ago']];
const stages=['New lead','Contacted','Qualified','Proposal','Won'];
function Table({headers,rows}:{headers:string[],rows:string[][]}){return <div className="tableWrap"><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===r.length-1&&['Hot','Warm','New','Scheduled','Running','Completed','New lead','Contacted','Qualified','Proposal','Won'].includes(c)?<span className={`badge ${['Hot','Won','Completed'].includes(c)?'green':['Warm','Scheduled','Proposal'].includes(c)?'orange':'blue'}`}>{c}</span>:c}</td>)}</tr>)}</tbody></table></div>}
function Card({title,children,action}:{title:string,children:React.ReactNode,action?:string}){return <section className="card"><div className="sectionTitle"><h2>{title}</h2>{action&&<button className="btn">{action}</button>}</div>{children}</section>}
export default function Home(){
 const [active,setActive]=useState('Dashboard'); const [open,setOpen]=useState(false);
 const go=(x:string)=>{setActive(x);setOpen(false)};
 const render=()=>{
  if(active==='Contacts') return <><div className="pageHead"><div><h1>Contacts</h1><div className="muted small">Customer 360, consent, location and engagement history.</div></div><button className="btn primary"><Plus size={16}/> Add contact</button></div><div className="grid4">{[['Total contacts','12,480'],['Opted in','11,940'],['Hot leads','384'],['Unassigned','42']].map(x=><div className="card kpi"><div><div className="label">{x[0]}</div><div className="value">{x[1]}</div></div></div>)}</div><Card title="Customer directory" action="Import / Export"><Table headers={['Name','Company','Phone','Location','Status']} rows={contacts}/></Card></>;
  if(active==='Companies') return <><div className="pageHead"><div><h1>Companies</h1><div className="muted small">Accounts and organizations linked to your contacts and deals.</div></div><button className="btn primary"><Plus size={16}/> Add company</button></div><Card title="Company accounts"><Table headers={['Company','Industry','Location','Contacts','Pipeline']} rows={companies}/></Card></>;
  if(active==='Leads') return <><div className="pageHead"><div><h1>Leads</h1><div className="muted small">Capture, qualify and follow up with every opportunity.</div></div><button className="btn primary"><Plus size={16}/> New lead</button></div><div className="grid4">{[['New','84'],['Contacted','52'],['Qualified','31'],['Hot','17']].map(x=><div className="card kpi"><div><div className="label">{x[0]}</div><div className="value">{x[1]}</div></div></div>)}</div><Card title="Lead queue"><Table headers={['Lead','Company','Source','Location','Status']} rows={contacts.map(x=>[x[0],x[1],'Business Finder',x[3],x[4]])}/></Card></>;
  if(active==='Deals') return <><div className="pageHead"><div><h1>Deals</h1><div className="muted small">Manage pipeline, value, probability and next activity.</div></div><button className="btn primary"><Plus size={16}/> New deal</button></div><div className="pipeline">{stages.map(s=><div className="stage"><div className="stageHead"><span>{s}</span><span>{deals.filter(d=>d[2]===s).length}</span></div>{deals.filter(d=>d[2]===s).map(d=><div className="deal"><b>{d[0]}</b><div className="muted small">{d[1]}</div></div>)}</div>)}</div></>;
  if(active==='Campaigns') return <><div className="pageHead"><div><h1>Campaigns</h1><div className="muted small">Create once, adapt across channels, schedule and measure.</div></div><button className="btn primary"><Plus size={16}/> New campaign</button></div><div className="quick"><button className="btn soft">WhatsApp</button><button className="btn">Email</button><button className="btn">Facebook + Instagram</button><button className="btn">X / Twitter</button></div><Card title="Campaigns"><Table headers={['Campaign','Channels','Status','Schedule / Reach']} rows={campaigns}/></Card></>;
  if(active==='Inbox') return <><div className="pageHead"><div><h1>Unified Inbox</h1><div className="muted small">WhatsApp, social, email and SMS conversations in one workspace.</div></div></div><div className="inboxGrid"><Card title="Conversations"><div className="conversation"><b>Priya Sharma</b><span className="badge green">WhatsApp</span><p className="muted small">Can someone call me about the weekend offer?</p></div><div className="conversation"><b>Rahul Kumar</b><span className="badge blue">Email</span><p className="muted small">Please send the updated quotation.</p></div><div className="conversation"><b>Bright Dental</b><span className="badge orange">Instagram</span><p className="muted small">Do you provide bulk pricing?</p></div></Card><Card title="Conversation"><div className="chat"><div className="bubble">Hello Priya! How can we help?</div><div className="bubble me">I can arrange a callback for you.</div></div><input className="input" placeholder="Type a reply..."/></Card></div></>;
  if(active==='Calls') return <><div className="pageHead"><div><h1>Calls</h1><div className="muted small">Click-to-call, callbacks, agent activity and call history.</div></div><button className="btn primary"><Phone size={16}/> Start call</button></div><div className="grid4">{[['Calls today','73'],['Connected','61'],['Callbacks','12'],['Avg duration','04:32']].map(x=><div className="card kpi"><div><div className="label">{x[0]}</div><div className="value">{x[1]}</div></div></div>)}</div><Card title="Call history"><Table headers={['Customer','Number','Direction','Agent','Status']} rows={contacts.map(x=>[x[0],x[2],'Outbound','MG','Connected'])}/></Card></>;
  if(active==='Business Finder') return <><div className="pageHead"><div><h1>Business Finder</h1><div className="muted small">Discover permitted public business information by category and location.</div></div><button className="btn primary"><Search size={16}/> Search</button></div><div className="finder"><Card title="Search criteria"><div className="formGrid"><input className="input" placeholder="Business category e.g. dental clinics"/><input className="input" placeholder="City / PIN / area"/><select className="input"><option>10 km radius</option><option>25 km radius</option><option>50 km radius</option></select><button className="btn primary">Find businesses</button></div></Card><Card title="Results"><Table headers={['Business','Category','Address','Phone','Source']} rows={[['Bright Dental','Dental','Whitefield, Bengaluru','Public listing','Licensed source'],['Green Leaf Foods','Restaurant','HSR Layout, Bengaluru','Public listing','Licensed source'],['Nova Fitness','Gym','Indiranagar, Bengaluru','Public listing','Licensed source']]}/></Card></div></>;
  if(active==='Analytics') return <><div className="pageHead"><div><h1>Analytics</h1><div className="muted small">Campaign, sales and channel performance.</div></div><button className="btn">Last 30 days</button></div><div className="grid4">{[['Messages sent','18,420'],['Delivery','96.4%'],['Clicks','3,842'],['Conversions','684']].map(x=><div className="card kpi"><div><div className="label">{x[0]}</div><div className="value">{x[1]}</div></div></div>)}</div><Card title="Channel performance"><div className="chart">{[40,65,52,78,60,86,72,94,76,98].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}/>)}</div></Card></>;
  if(active==='AI Assistant') return <><div className="pageHead"><div><h1>AI Assistant</h1><div className="muted small">Your CRM copilot for customers, campaigns, sales and analytics.</div></div></div><div className="aiHero"><Bot size={28}/><div><h2>Ask Promote_Me</h2><p className="muted">Summarize a customer, draft a campaign, find leads, explain analytics or prepare a follow-up.</p></div></div><Card title="Suggested actions"><div className="quick"><button className="btn soft">Summarize today's leads</button><button className="btn">Draft a WhatsApp promotion</button><button className="btn">Find similar businesses</button><button className="btn">Show overdue follow-ups</button></div></Card></>;
  if(active==='Settings') return <><div className="pageHead"><div><h1>Settings</h1><div className="muted small">Accounts, security, integrations and business configuration.</div></div></div><div className="settingsGrid">{[['Business profile',Building2,'Name, address, timezone'],['WhatsApp',MessageCircle,'Business account and templates'],['Facebook & Instagram',Globe,'Pages, profiles and tokens'],['X / Twitter',Globe,'API connection'],['Email',Mail,'SMTP / provider'],['Calling',Phone,'Telephony and agents'],['AI',Bot,'Provider and knowledge base'],['Users & roles',Users,'Permissions and access'],['Security',ShieldCheck,'Secrets, 2FA and audit log']].map(([t,I,d]:any)=><button className="settingCard" key={t as string}><I size={20}/><div><b>{t}</b><p className="muted small">{d}</p></div><ChevronRight size={16}/></button>)}</div></>;
  if(active==='Automations') return <><div className="pageHead"><div><h1>Automations</h1><div className="muted small">Build customer journeys and follow-up workflows.</div></div><button className="btn primary"><Plus size={16}/> New automation</button></div><Card title="Active workflows"><div className="flow"><span>Lead created</span><ChevronRight/><span>Wait 2 days</span><ChevronRight/><span>Send WhatsApp</span><ChevronRight/><span>If clicked → assign agent</span></div></Card></>;
  if(active==='Activities') return <><div className="pageHead"><div><h1>Activities</h1><div className="muted small">Calls, notes, meetings, messages and tasks.</div></div><button className="btn primary"><Plus size={16}/> Log activity</button></div><Card title="Timeline">{activities.map(a=><div className="activity"><div className="dot"/><div><b>{a[0]}</b> · {a[1]}<div className="muted small">{a[2]}</div></div></div>)}</Card></>;
  return <><div className="pageHead"><div><h1>Good evening, Mudigouda</h1><div className="muted small">Wednesday, August 19 · Your CRM command center.</div></div><button className="btn primary" onClick={()=>setOpen(!open)}><Plus size={16}/> New campaign</button></div>{open&&<div className="card" style={{marginBottom:16}}><b>Quick campaign</b><p className="muted small">Choose an audience, channel and schedule.</p><div className="quick"><button className="btn soft">WhatsApp</button><button className="btn">Email</button><button className="btn">Social</button><button className="btn">AI draft</button></div></div>}<section className="grid4">{[['Contacts','12,480','+8.2%'],['Pipeline','₹18.6L','+12.4%'],['Campaigns','8','+2 this week'],['Conversion','6.8%','+1.1%']].map(x=><div className="card kpi"><div><div className="label">{x[0]}</div><div className="value">{x[1]}</div></div><span className="trend">{x[2]}</span></div>)}</section><div className="grid3" style={{marginTop:16}}><Card title="Sales pipeline" action="View all"><div className="pipeline">{stages.map(s=><div className="stage"><div className="stageHead"><span>{s}</span><span>{deals.filter(d=>d[2]===s).length}</span></div>{deals.filter(d=>d[2]===s).map(d=><div className="deal"><b>{d[0]}</b><div className="muted small">{d[1]}</div></div>)}</div>)}</div></Card><Card title="Campaign performance"><div className="chart">{[42,60,48,75,55,84,68,92,70,98].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}/>)}</div><div className="muted small">Delivery · 96.4%</div></Card></div><div className="grid3" style={{marginTop:16}}><Card title="Recent campaigns"><Table headers={['Campaign','Channels','Status','Reach']} rows={campaigns}/></Card><Card title="Needs attention">{[['8','Overdue follow-ups'],['14','Leads waiting'],['5','Callbacks'],['3','AI recommendations']].map(x=><div className="activity"><div className="dot"/><div><b>{x[0]}</b> <span className="muted small">{x[1]}</span></div></div>)}</Card><Card title="Customer 360"><p className="muted">Every customer can have contacts, company, deals, conversations, calls, campaigns, location, notes and AI summary in one record.</p><button className="btn soft" onClick={()=>go('Contacts')}>Open contacts</button></Card></div></>;
 };
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandMark">P</div>Promote_Me</div>{nav.map(([section,items]:any)=><div key={section}><div className="navSection">{section}</div>{items.map(([label,Icon]:any)=><button key={label} className={`navItem ${active===label?'active':''}`} onClick={()=>go(label)}><Icon size={16}/>{label}</button>)}</div>)}</aside><div className="main"><header className="topbar"><button className="iconBtn mobileOnly"><Menu size={18}/></button><div className="search"><Search size={16}/><input placeholder="Search contacts, companies, deals..."/><kbd className="hideMobile">⌘ K</kbd></div><div className="actions"><button className="iconBtn"><Bell size={17}/></button><button className="iconBtn" onClick={()=>go('AI Assistant')}><Bot size={17}/></button><div className="avatar">MG</div></div></header><main className="content">{render()}</main></div><nav className="bottomNav"><button onClick={()=>go('Dashboard')} className={active==='Dashboard'?'active':''}><Home size={18}/>Home</button><button onClick={()=>go('Leads')}><Target size={18}/>Leads</button><button onClick={()=>go('Inbox')}><Inbox size={18}/>Inbox</button><button onClick={()=>go('Calls')}><Phone size={18}/>Calls</button><button onClick={()=>setOpen(!open)}><Menu size={18}/>More</button></nav></div>
}