import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { COOKIE_NAME, getSessionUser } from "../../src/lib/auth";
import { prisma } from "../../src/lib/prisma";

export default async function ContactsPage(){
 const user=await getSessionUser((await cookies()).get(COOKIE_NAME)?.value); const m=user?.memberships[0]; if(!user||!m) redirect('/login');
 const contacts=await prisma.contact.findMany({where:{businessId:m.businessId},orderBy:{createdAt:'desc'}});
 return <main style={{minHeight:'100vh',background:'#f6f7fb',padding:'32px 20px',fontFamily:'system-ui'}}><div style={{maxWidth:1100,margin:'auto'}}><a href="/dashboard">← Dashboard</a><h1 style={{marginBottom:6}}>Contacts</h1><p style={{color:'#667085'}}>Add and manage your business contacts. Blank submissions are blocked.</p><section style={{background:'#fff',border:'1px solid #e4e7ec',borderRadius:14,padding:20,boxShadow:'0 2px 8px rgba(16,24,40,.05)'}}><form action="/api/contacts" method="post" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:14}}>{[['firstName','First name'],['lastName','Last name'],['company','Company'],['phone','Phone'],['email','Email'],['city','City'],['region','State / Region'],['country','Country']].map(([name,label])=><label key={name} style={{display:'grid',gap:6,fontWeight:600}}>{label}<input name={name} placeholder={label} required={['firstName','company','phone'].includes(name)} style={{padding:'11px 12px',border:'1px solid #d0d5dd',borderRadius:9,fontSize:15}}/></label>)}<div style={{gridColumn:'1/-1'}}><button type="submit" style={{padding:'11px 18px',border:0,borderRadius:9,cursor:'pointer'}}>Add Contact</button></div></form></section><section style={{marginTop:22,background:'#fff',border:'1px solid #e4e7ec',borderRadius:14,overflow:'hidden'}}><div style={{padding:18,borderBottom:'1px solid #e4e7ec'}}><strong>{contacts.length} contact{contacts.length===1?'':'s'}</strong></div>{contacts.length===0?<p style={{padding:20,color:'#667085'}}>No contacts yet.</p>:contacts.map(c=><article key={c.id} style={{padding:18,borderBottom:'1px solid #eef0f3'}}><strong style={{fontSize:16}}>{[c.firstName,c.lastName].filter(Boolean).join(' ')}</strong><div style={{color:'#475467',marginTop:5}}>{c.company}{c.phone?` · ${c.phone}`:''}{c.email?` · ${c.email}`:''}</div><div style={{color:'#667085',fontSize:14,marginTop:4}}>{[c.city,c.region,c.country].filter(Boolean).join(', ')}</div></article>)}</section></div></main>
}
